name: flutter_app
description: The App for I Want That

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.1.1
  firebase_vertexai: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  image_picker: 1.1.2

flutter:
  uses-material-design: true